import os

class PathApprover:
	"""Per-project path approval manager.
	Loads from and saves to PROJECT.md in the working directory.
	Controls which directories and files tools can access."""

	SECTION_HEADERS = {
		'approved_dirs' : '## Approved Directories',
		'approved_files': '## Approved Files',
		'denied_paths'  : '## Denied Paths',
	}

	def __init__(self, working_dir=None):
		self.working_dir   = working_dir
		self.project_file  = os.path.join(working_dir, 'PROJECT.md') if working_dir else None
		self.approved_dirs  = set()
		self.approved_files = set()
		self.denied_paths   = set()
		self._load()

	def _load(self):
		self.approved_dirs  = set()
		self.approved_files = set()
		self.denied_paths   = set()
		if not self.project_file or not os.path.exists(self.project_file):
			self.approved_dirs.add('.')
			return
		current_section = None
		with open(self.project_file, 'r') as f:
			for line in f:
				stripped = line.strip()
				if not stripped:
					continue
				for key, header in self.SECTION_HEADERS.items():
					if stripped.startswith(header):
						current_section = key
						break
				else:
					if stripped.startswith('#'):
						continue
					if current_section == 'approved_dirs':
						self.approved_dirs.add(stripped)
					elif current_section == 'approved_files':
						self.approved_files.add(stripped)
					elif current_section == 'denied_paths':
						self.denied_paths.add(stripped)

	def save(self):
		if not self.project_file:
			return
		with open(self.project_file, 'w') as f:
			f.write("# Project Path Approvals\n")
			f.write("# Generated by OurAI. Edit manually or use !PROJECT commands.\n")
			f.write("# Paths are relative to the project root.\n")
			f.write("\n")
			f.write("## Approved Directories\n")
			for d in sorted(self.approved_dirs):
				f.write(d + "\n")
			f.write("\n")
			f.write("## Approved Files\n")
			for fp in sorted(self.approved_files):
				f.write(fp + "\n")
			f.write("\n")
			f.write("## Denied Paths\n")
			for d in sorted(self.denied_paths):
				f.write(d + "\n")

	def _resolve(self, path):
		if not path:
			return None
		if os.path.isabs(path):
			base = os.path.normpath(path)
		else:
			candidate = os.path.join(self.working_dir, path) if self.working_dir else path
			base = os.path.normpath(candidate)
		if os.path.exists(base):
			return os.path.realpath(base)
		parent = os.path.dirname(base)
		if os.path.exists(parent):
			return os.path.join(os.path.realpath(parent), os.path.basename(base))
		return base

	def _is_within(self, path, container):
		if not path or not container:
			return False
		if path == container:
			return True
		sep = container.rstrip('/') + '/'
		os_sep = container.rstrip(os.sep) + os.sep
		return path.startswith(sep) or path.startswith(os_sep)

	def is_allowed(self, raw_path):
		if not raw_path:
			return True
		resolved = self._resolve(raw_path)
		if not resolved:
			return True
		for deny_path in self.denied_paths:
			denied_resolved = self._resolve(deny_path)
			if denied_resolved and self._is_within(resolved, denied_resolved):
				return False
		for af in self.approved_files:
			af_resolved = self._resolve(af)
			if af_resolved and resolved == af_resolved:
				return True
		for ad in self.approved_dirs:
			ad_resolved = self._resolve(ad)
			if ad_resolved and self._is_within(resolved, ad_resolved):
				return True
		return False

	def add_dir(self, path):
		self.approved_dirs.add(path)

	def add_file(self, path):
		self.approved_files.add(path)

	def deny(self, path):
		self.denied_paths.add(path)
